Metrics/LineLength:
  Max: 120

Layout/IndentHash:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MixinUsage:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/SymbolArray:
  Enabled: false
