AllCops:
  Exclude:
    - db/schema.rb

inherit_mode:
  merge:
    - Exclude

Metrics/AbcSize:
  Max: 15.33

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 15

Layout/IndentHash:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MixinUsage:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/SymbolArray:
  Enabled: false
