require: rubocop-performance

AllCops:
  Exclude:
    - db/schema.rb

inherit_mode:
  merge:
    - Exclude

Layout/LineLength:
  Max: 120

Layout/FirstHashElementIndentation:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/MixinUsage:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/OptionalBooleanParameter:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/SymbolArray:
  Enabled: false
